version: '3'

services:
  database:
    image: mysql
    container_name: redisson_db
    environment:
      MYSQL_DATABASE: redisson
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redisson_redis
#    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
