spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redisson?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '1234'

    hikari:
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
